### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by vipermetcaff** [mafe72/Retroflag-NESPi-Front-Panel-Control-Board#2]
i'm having a problem the reset button isn't working the power button work great

**Comment by mafe72** [comment]
Starting version v1.02, the reset button will no longer reboot the console, then new functionality is as follows:
- During game time, press reset button to Restart the current game.
- During game time, hold the reset button for 3 sec to Quit the current game and return to the Retropie dashboard.

**Comment by vipermetcaff** [comment]
when im in a game  like nes it will only reset once then when i hit the reset again it doesnt reset the game
