### ISSUE TITLE
DIY PCB/BOM informations missing + a bug

### ISSUE THREAD

**Issue by RRAlex** [mafe72/Retroflag-NESPi-Front-Panel-Control-Board#4]
I like this NesPi mod solution and thanks to this repository I was able to build a complete NesPi myself with the OSHpark & the BOM list links. I learned a few things about electronic, GPIO programming, the Pi along the way too!

It seems the PCB & BOM links went missing from the repo's master branch since than and the oshpark link ( https://oshpark.com/shared_projects/ssSJDKKQ ) is gone?

I also realized you have updated your design and was wondering if the source for the new one was going to be made available for those wanting to try their hand at weekend Pi soldering/GPIO project?
Or, simply, leave the older design up for people wanting to DIY the old fashioned way and keep the latest until you improve it again?

I'm pretty sure the DIY community is a very small one, but at the same time cool contributions could come from this repo acting as the central project of NesPi mods instead of spreading them around in various repos & forums.

Anyway, just wanted to pitch in as a fan of this project and of open source hardware communities... :)
Cheers and thanks for everything!

P.S. There is a typo on the line linked below: `apt-get` not `apt - get` :)
https://github.com/mafe72/Retroflag-NESPi-Front-Panel-Control-Board/blob/master/install.sh#L55

**Comment by mafe72** [comment]
Oshpark link is permanently gone, you can get the latest Gerber files from the repo. I have fix the typo, thanks for your interest on this project.
